import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Menu } from "../layouts/menu/Menu";
import { DrawerLayout } from "@/layouts/drawer/DrawerLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" style={{ overflowX: "hidden" }}>
      <body className={inter.className}>
        <DrawerLayout>
          {" "}
          <Menu /> {children}
        </DrawerLayout>
      </body>
    </html>
  );
}
